package net.hwyz.iov.vehicle.ivi.ivai.agent

/**
 * Agent state machine (IVI-IVAI-DSN-CR-001 + CR-005):
 * RECEIVED → NORMALIZED → TIER_ROUTED
 *   ├─ L0_MATCHED → CANDIDATE_READY → VALIDATED
 *   │    ├─ NEED_DIALOGUE → WAITING_USER → 恢复任务
 *   │    ├─ CLOUD_REQUIRED
 *   │    ├─ REJECTED
 *   │    └─ AUTHORIZED → EXECUTING → SUCCEEDED / FAILED / TIMEOUT → REPORTED
 *   ├─ L1_RETRIEVING_TOOLS → MODEL_REQUESTED → MODEL_RESPONDED → PARSED → CANDIDATE_READY → …
 *   ├─ L2_RETRIEVING_KNOWLEDGE → MODEL_REQUESTED → MODEL_RESPONDED → REPLY
 *   ├─ L3_CLOUD_REQUIRED
 *   └─ REJECTED
 */
enum class AgentState {
    RECEIVED,
    NORMALIZED,
    TIER_ROUTED,
    L0_MATCHED,
    L1_RETRIEVING_TOOLS,
    L2_RETRIEVING_KNOWLEDGE,
    CANDIDATE_READY,
    MODEL_REQUESTED,
    MODEL_RESPONDED,
    PARSED,
    VALIDATED,
    NEED_DIALOGUE,
    WAITING_USER,
    REPLY_READY,
    CLOUD_REQUIRED,
    REJECTED,
    AUTHORIZED,
    EXECUTING,
    SUCCEEDED,
    FAILED,
    TIMEOUT,
    REPORTED
}
